import {StyleSheet} from 'react-native';
import {COLORS, SIZES, FONTS} from '../../constants/Theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 80,
  },
  scrollImage: {
    width: SIZES.width * 0.8,
    marginRight: 10,
    height: '90%',
    borderRadius: 10,
  },
  pmCareCard: {
    elevation: 5,
    backgroundColor: 'white',
    shadowOffset: {width: 1, height: 1},
    shadowColor: '#333',
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 20,
    padding: 10,
    borderRadius: 5,
    shadowOpacity: 0.3,
    shadowRadius: 2,
  },
  cardText: {
    color: COLORS.primary,
    ...FONTS.h3,
  },
  cardTextWhite: {
    color: 'white',
    ...FONTS.h3,
  },
  footer: {
    elevation: 5,
    backgroundColor: COLORS.secondary,
    shadowOffset: {width: 1, height: 1},
    shadowColor: '#333',
    padding: 15,
    width: '100%',
    marginTop: 10,
    borderTopEndRadius: 20,
    borderTopStartRadius: 20,
    shadowOpacity: 0.3,
    shadowRadius: 2,
  },
  footerText: {
    ...FONTS.body4,
    color: 'white',
    textAlign: 'center',
  },
  card: {
    elevation: 5,
    backgroundColor: 'white',
    shadowOffset: {width: 1, height: 1},
    shadowColor: '#333',
    padding: 10,
    marginVertical: 10,
    width: '100%',
    borderRadius: 10,
    shadowOpacity: 0.3,
    shadowRadius: 2,
  },
  cardBlue: {
    elevation: 5,
    backgroundColor: COLORS.secondary,
    shadowOffset: {width: 1, height: 1},
    shadowColor: '#333',
    padding: 10,
    marginVertical: 10,
    width: '100%',
    borderRadius: 10,
    shadowOpacity: 0.3,
    shadowRadius: 2,
  },
  button: {
    flexDirection: 'row',
    backgroundColor: COLORS.primary,
    marginTop: 10,
    justifyContent: 'center',
    alignContent: 'center',
    borderRadius: 3,
    elevation: 5,
    padding: 5,
  },
});
